### ISSUE TITLE
MEMFAULT_PLATFORM_COREDUMP_STORAGE_PARTITION unused

### ISSUE THREAD

**Issue by hh-decr** [memfault/memfault-firmware-sdk#10]
It appears that the partition NVMS_LOG_PART is hardcoded and was intended to be swapped with  MEMFAULT_PLATFORM_COREDUMP_STORAGE_PARTITION in the code but wasn't. 

See:
https://github.com/memfault/memfault-firmware-sdk/commit/1a64c90026bee493f6f92fdb760340b715c4b84d#diff-1b48dc0a21698d35d6e9d452f6a0177c4914d391f245db0d81b2d8a68794ab5aR117

https://github.com/memfault/memfault-firmware-sdk/commit/1a64c90026bee493f6f92fdb760340b715c4b84d#diff-1b48dc0a21698d35d6e9d452f6a0177c4914d391f245db0d81b2d8a68794ab5aR124

**Comment by chrisc11** [comment]
Thanks for the report @hh-decr ... looks like you are right, we'll get that patched up!

**Comment by chrisc11** [comment]
Fixed in release 0.16.1, thanks for the report!
