### ISSUE TITLE
Warnings generated in Code Composer Studio

### ISSUE THREAD

**Issue by albertskog** [memfault/memfault-firmware-sdk#18]
I noticed since a recent SDK upgrade to `0.24.1` we are getting a couple of these build warnings in `memfault-firmware-sdk/components/panics/src/memfault_fault_handling_arm.c`:

`#1585-D function declared with "noreturn" does return`

I'm using CCS 10.1 and TI CC2652

![image](https://user-images.githubusercontent.com/706444/131807093-8379a68d-abf5-42b9-bca9-89749c48e831.png)

**Comment by franc0is** [comment]
Thanks for the note @albertskog. These warnings are innocuous but we'll fix them up.

**Comment by chrisc11** [comment]
Thanks for the report! This was fixed in the 0.26.0 release
