### ISSUE TITLE
Outdated Memfault.cmake comment

### ISSUE THREAD

**Issue by C47D** [memfault/memfault-firmware-sdk#21]
There's a reference to a file named `MemfaultWorker.cmake` in the header of the Memfault.cmake file, a similar file named `MemfaultWorker.mk` is located in the makefiles directory.

https://github.com/memfault/memfault-firmware-sdk/blob/8585f81453af37cd97c47816cc61395cbabdf1fe/cmake/Memfault.cmake#L10

**Comment by chrisc11** [comment]
Thanks for the report! This was fixed in the  0.28.0 release!
