### ISSUE TITLE
Heap stats free not checking in_use flag

### ISSUE THREAD

**Issue by christophgreen** [memfault/memfault-firmware-sdk#32]
In **memfault_heap_stats_free**, there is not a check to make sure the heap item pointer is actually in use. It is only checking the pointer against the items in the stats pool. However, there can be multiple items with the same address in the pool (of which only one is currently in use). This free check doesn't account for that and will exit after the first entry that it sees. 

Here is the simple case where this happens:

alloc() --> return address **X**
free(P1) 
alloc() --> return address **X** --- Now the heap stats will have 2 entries for items at address **X**, one is in_use and the other is not.
free() --> The heap stats will now be incorrect as it will mark the first entry (which is already not in use) and skip the second entry. 

An example of what could fix the issue:

```
--- a/components/core/src/memfault_heap_stats.c
+++ b/components/core/src/memfault_heap_stats.c
@@ -93,7 +93,7 @@ void memfault_heap_stats_free(const void *ptr) {
 
     // if the pointer exists in the tracked stats, mark it as freed
     for (size_t i = 0; i < MEMFAULT_ARRAY_SIZE(g_memfault_heap_stats_pool); i++) {
-      if (g_memfault_heap_stats_pool[i].ptr == ptr) {
+      if (g_memfault_heap_stats_pool[i].ptr == ptr && g_memfault_heap_stats_pool[i].info.in_use == 1) {
         g_memfault_heap_stats_pool[i].info.in_use = 0;
         break;
       }
```

**Comment by noahp** [comment]
FYI @christophgreen this fix has been published in [v0.33.1](https://github.com/memfault/memfault-firmware-sdk/releases/tag/0.33.1), let us know if there's any issues!
