### ISSUE TITLE
zephyr: `memfault_zephyr_log_backend_disable` called even without `CONFIG_MEMFAULT_LOGGING_ENABLE`

### ISSUE THREAD

**Issue by JordanYates** [memfault/memfault-firmware-sdk#56]
`memfault_zephyr_log_backend_disable` is called here: https://github.com/memfault/memfault-firmware-sdk/blob/73ec7b7c020d9183f264c45c0fa3d3f2b9238aa1/ports/zephyr/common/memfault_platform_core.c#L52

Even when `CONFIG_MEMFAULT_LOGGING_ENABLE=n`, resulting in compilation errors.

**Comment by noahp** [comment]
@JordanYates thanks for reporting, this will be fixed ASAP!

**Comment by noahp** [comment]
@JordanYates FYI this is fixed in SDK v1.1.2, published now:
https://github.com/memfault/memfault-firmware-sdk/releases/tag/1.1.2

Thanks again for reporting, and let us know if there's any problem!
