### ISSUE TITLE
Memfault uses a deprecated Zephyr type: `z_arch_esf_t`

### ISSUE THREAD

**Issue by carlescufi** [memfault/memfault-firmware-sdk#74]
`z_arch_esf_t` is now `struct arch_esf `

See:

https://github.com/zephyrproject-rtos/zephyr/pull/73593

**Comment by noahp** [comment]
Thank you @carlescufi for reporting- I've pushed a branch in #75 for verification, let us know if it's working and we'll publish an official release of the SDK.

**Comment by noahp** [comment]
Fix was published in SDK release 1.12.0, thanks again for reporting the issue!
